<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <script>
    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        reject({
          errCode: 1000,
          message: 'xxx出错了'
        })
      }, 1000);
    })


    // 异步操作失败后，会调用catch回调函数
    // 但是错误被catch捕获后，后面的代码就不会执行
    p.catch(err => {
        console.log(err)
      })
      .catch(() => {
        console.log(2222)
      })
  </script>
</body>

</html>